In [1]:
import folium
import geopandas as gpd
import pandas as pd

In [43]:
polbndry = gpd.read_file("Lab3_Dataset/polbndry.shp")
place = gpd.read_file("Lab3_Dataset/places.shp")
tambon = gpd.read_file("Lab3_Dataset/tambon.dbf",encoding='tis-620')
pl_type = gpd.read_file("Lab3_Dataset/PL_TYPE.dbf",encoding='tis-620')

In [18]:
print(polbndry.crs)
print(place.crs)

None
None

In [44]:
polbndry = polbndry.set_crs('EPSG:24047')
place = place.set_crs('EPSG:24047')
print(polbndry.crs)
print(place.crs)

EPSG:24047
EPSG:24047

In [ ]:
print(polbndry.columns)
print(tambon.columns)
print(place.columns)
print(pl_type.columns)

Index(['AREA', 'PERIMETER', 'POLBNDRY_', 'POLBNDRY_I', 'TAMBON_IDN',
       'AMPHOE_IDN', 'PROV_CODE', 'AMP_CODE', 'TAM_CODE', 'AreaKM',
       'geometry'],
      dtype='object')
Index(['TAMBON_IDN', 'TAMBON_E', 'TAMBON_T'], dtype='object')
Index(['AREA', 'PERIMETER', 'PLACES_', 'PLACES_ID', 'PLACE_ID', 'PL_TYPE',
       'PL_NAME_E', 'PL_NAME_T', 'geometry'],
      dtype='object')
Index(['PL_TYPE', 'TYP_NAM_E', 'TYP_NAM_T'], dtype='object')

In [45]:
polbndry = polbndry.merge(tambon, on = 'TAMBON_IDN', how = 'left')
place = place.merge(pl_type, on = 'PL_TYPE', how = 'left')

In [24]:
polbndry.head()

,AREA,PERIMETER,POLBNDRY_,POLBNDRY_I,TAMBON_IDN,AMPHOE_IDN,PROV_CODE,AMP_CODE,TAM_CODE,AreaKM,geometry,TAMBON_E,TAMBON_T
0,442813900.0,108961.90,2,1,530604,5306,53,06,04,442.65,"POLYGON ((711403.375 2025106.875, 711438.375 2...",Bo Bia,บ่อเบี้ย
1,196510300.0,84420.59,3,2,530601,5306,53,06,01,196.42,"POLYGON ((728595.062 2017436.875, 728681.688 2...",Moung Jet Ton,ม่วงเจ็ดต้น
2,292816400.0,77798.30,4,3,530501,5305,53,05,01,292.74,"POLYGON ((702279.812 2008219.875, 702330.312 2...",Fak Tha,ฟากท่า
3,165066500.0,68847.11,5,6,530502,5305,53,05,02,165.04,"POLYGON ((688202.812 1994047.5, 688211.062 199...",Song Kon,สองคอน
4,124675900.0,63177.66,6,4,530602,5306,53,06,02,124.62,"POLYGON ((716447.5 1997946.375, 716496.125 199...",Ban Khok,บ้านโคก

In [ ]:
place.head()

,AREA,PERIMETER,PLACES_,PLACES_ID,PLACE_ID,PL_TYPE,PL_NAME_E,PL_NAME_T,geometry,TYP_NAM_E,TYP_NAM_T
0,0.0,0.0,1,1,NaN,8,O.B.T. Tham Chalong,อบต.ถ้ำฉลอง,POINT (643631 1946172),RTG,สถานที่ราชการ
1,0.0,0.0,2,2,NaN,8,O.B.T. Nam Phi,อบต.น้ำพี้,POINT (636048 1941902),RTG,สถานที่ราชการ
2,0.0,0.0,3,3,NaN,8,O.B.T. Tha Sao,อบต.ท่าเสา,POINT (616803 1952550),RTG,สถานที่ราชการ
3,0.0,0.0,4,4,NaN,8,O.B.T. Ban Dan,อบต.บ้านด่าน,POINT (636305 1953375),RTG,สถานที่ราชการ
4,0.0,0.0,5,5,NaN,8,O.B.T. Ngew Ngam,อบต.งิ้วงาม,POINT (624999 1953438),RTG,สถานที่ราชการ

In [51]:
school = place[place['TYP_NAM_T'] == 'โรงเรียน'].copy()
school['geometry'] = school.buffer(5000)
schoolbuff5k = school.dissolve()
schoolbuff5k_clip = gpd.clip(schoolbuff5k, polbndry)

In [52]:
m = folium.Map(location=[17.742408, 100.569862], zoom_start=9)
folium.GeoJson(schoolbuff5k_clip,name='schoolbuff5k').add_to(m)
folium.LayerControl().add_to(m)
m.save("map_lab3.html")